const text= `Holes,
Reservoir Dogs,
Kill Bill: Vol. 1,
Kill Bill: Vol. 2,
Django Unchained,
Fight Club,
Inception,
Interstellar,
Alien,
Predators,
Scarface,
Forrest Gump,
Se7en,
The Shawshank Redemption,
Life Is Beautiful,
Let the Right One In,
Back to the Future,
Back to the Future Part II,
Back to the Future Part III,
The Dark Knight,
The Dark Knight Rises,
Batman Begins,
The Shining,
Whiplash,
The Italian Job,
Toy Story,
Toy Story 2,
Toy Story 3,
Monsters Inc,
Brave,
WALL·E,
The Incredibles,
Up,
A Bugs Life,
Finding Nemo,
Finding Dory,
Ratatouille,
Cars,
Cars 2,
The Wolf of Wall Street,
Titanic,
Silence,
Cinema Paradiso,
Shutter Island,
The Princess Bride,
The Big Short,
Roman Holiday,
Big Daddy,
The Revenant,
Wanted,
Elf,
Ocean's Eleven,
Mad Max: Fury Road,
The Bourne Identity,
The Bourne Supremacy,
The Bourne Ultimatum,
The Bourne Legacy,
Tropic Thunder,
Jason Bourne,
Avatar,
The Hitchhiker's Guide to the Galaxy,
The Prestige,
Sherlock Holmes,
The Fast and the Furious,
2 Fast 2 Furious,
The Fast and the Furious: Tokyo Drift,
Fast & Furious,
Fast Five,
Fast & Furious 6,
Furious 7,
The Fate of the Furious,
Snowpiercer,
La Bamba,
Under the Same Moon,
Mrs. Doubtfire,
Jumanji,
Zathura: A Space Adventure,
School of Rock,
Nacho Libre,
Kung Fu Panda,
Kung Fu Panda 2,
Superbad,
Scott Pilgrim vs. the World,
21 Jump Street,
22 Jump Street,
The Chronicles of Narnia: The Lion, the Witch and the Wardrobe,
The Chronicles of Narnia: The Voyage of the Dawn Treader,
Remember the Titans,
Coach Carter,
Glory Road,
Goal! The Dream Begins,
Gran Torino,
Raiders of the Lost Ark,
Indiana Jones and the Temple of Doom,
Indiana Jones and the Last Crusade,
Indiana Jones and the Kingdom of the Crystal Skull,
The Mask of Zorro,
The Legend of Zorro,
Borat,
Anger Management,
Prisoners,
Flightplan,
Source Code,
Léon: The Professional,
Doctor Strange,
The Usual Suspects,
Casablanca,
American Psycho,
Elite Squad,
Minority Report,
Memento,
No Country for Old Men,
Sicario,
Suicide Squad,
Apocalypto,
Independence Day,
Spectre,
Ant-Man,
The Boss Baby,
Spider-Man,
Spider-Man 2,
The Amazing Spider-Man,
Spider-Man 3,
The Disaster Artist,
Coco,
Wonder Woman,
Equilibrium,
Arrival,
The Big Sick,
Push,
In Time,
The Colony,
Life as We Know It,
The Hot Chick,
White House Down,
White Chicks,
The Other Guys,
Cop Out,
Rise of the Planets of the Apes,
RED,
The Wolverine,
Wreck-it Ralph,
Safe,
House at the End of the Street,
Taken,
Taken 2,
The Grey,
Skyfall,
The Hobbit: An Unexpected Journey,
Pirates of the Caribbean: At World's End,
Pirates of the Caribbean: The Curse of the Black Pearl,
Pirates of the Caribbean: Dead Man's Chest,
Mission: Impossible - Ghost Protocol,
The Pursuit of Happyness,
Transformers,
Troy,
Blue Streak,
Ex Machina,
Death at a Funeral,
Transformers: Dark of the Moon,
Next Friday,
Rush Hour 3,
Rush Hour,
Rush Hour 2,
Sherlock Holmes: A Game of Shadows,
Faster,
Sky High,
Apollo 18,
Knight and Day,
Are We Done Yet?,
Are We There Yet?,
I Am Number Four,
Hancock,
The Book of Eli,
I Am Legend,
Man on a Ledge,
Iron Man,
Thor,
The Avengers,
The Hunger Games,
G-Force,
High School Musical 2,
High School Musical,
Sydney White,
Oldboy,
The Truman Show,
Inglourious Basterds,
Jurassic Park,
The Matrix,
The Matrix Reloaded,
The Matrix Revolutions,
Speed,
The Lord of the Rings: The Return of the King,
The Lord of the Rings: The Fellowship of the Ring,
The Lord of the Rings: The Two Towers,
Pulp Fiction,
Night at the Museum,
Night at the Museum: Secret of the Tomb,
Alice in Wonderland,
Charlie and the Chocolate Factory,
Amélie,
Ocean's Twelve,
Ocean's Thirteen,
Nightcrawler,
Now You See Me,
Lucy,
Divergent,
The Hunger Games: Catching Fire,
The Hunger Games: Mockingjay - Part 1,
Thor: Ragnarok,
Thor: The Dark World,
Guardians of the Galaxy Vol. 2,
Avengers: Age of Ultron,
Guardians of the Galaxy,
Captain America: Civil War,
The Babadook,
Baby Driver,
La La Land,
The Curious Case of Benjamin Button,
The Golden Compass,
Cleopatra,
Spartacus,
The Place Beyond the Pines,
The Martian,
It,
Avengers: Infinity War,
Cars 3,
A Quiet Place,
Ocean's 8,
Extremely Loud & Incredibly Close,
Captain Phillips,
The Blind Side,
The Proposal,
The Terminal, 
The Incredibles 2,
Taxi Driver,
Hereditary,
Donnie Darko,
Inside Out,
BlacKkKlansman,
Black Panther,
The Hobbit: The Battle of the Five Armies,
The Hobbit: The Desolation of Smaug,
Be Kind Rewind,
The Green Hornet,
The Interview,
Pineapple Express,
Tower Heist,
This Is the End,
Neighbors,
Ted,
Ted 2,
We're the Millers,
Horrible Bosses,
Due Date,
300,
Now You See Me 2,
Anchorman: The Legend of Ron Burgundy,
Anchorman 2: The Legend Continues,
Talladega Nights: The Ballad of Ricky Bobby,
Step Brothers,
Dodgeball,
Zoolander,
Old School,
Get Smart,
G.I. Joe: Retaliation,
The Expendables,
The Expendables 2,
RED 2,
Death Race,
Cowboys & Aliens,
TRON: Legacy,
John Carter,
Prince of Persia: The Sands of Time,
Dracula Untold,
The Predator,
2012,
Battleship,
Moon,
The Founder,
Lady Bird,
A Simple Favor,
Get Out,
Bird Box,
Spider-Man: Into the Spider-Verse,
Hot Fuzz,
Game Night,
Don't Breathe,
Kingsman: The Secret Service,
Deadpool,
Deadpool 2,
John Wick,
John Wick 2,
John Wick 3,
Dawn of the Planet of the Apes,
Godzilla,
Annihilation,
Velvet Buzzsaw,
Ant-Man and the Wasp,
The Witch,
Dunkirk,
Eternal Sunshine of the Spotless Mind,
Roma,
Ready Player One,
Wonder,
Wayne's World,
Split,
12 Monkeys,
Stonehearst Asylum,
Public Enemies,
Takers,
The Equalizer,
Kingsman: The Golden Circle,
Ferris Bueller's Day Off,
RocknRolla,
Lawless,
Fury,
The Fighter,
The Lone Ranger,
The Tourist,
Salt,
Mr. & Mrs. Smith,
I Robot,
World War Z,
Men in Black,
Men in Black II,
Men in Black 3,
Edge of Tomorrow,
Looper,
Step Up,
The World's End,
Step Up All In,
Avengers: Endgame,
Bad Times at the El Royale,
The Lego Movie,
The LEGO Movie 2: The Second Part,
Just Go with It,
The Cabin in the Woods,
Grandma's Boy,
Ralph Breaks the Internet,
American Animals,
Jumanji: Welcome to the Jungle,
Bohemian Rhapsody,
Glass,
Captain Marvel,
Toy Story 4,
Us,
Spider-Man: Far from Home,
Escape Room,
Beats,
The Imitation Game,
Ad Astra,
6 Underground,
Snatch,
Knives Out,
Midsommar,
It Chapter Two,
The Departed,
Catch Me If You Can,
Logan,
Primer,
Underwater,
1917,
Alita: Battle Angel,
Contagion,
Once Upon a Time in Hollywood,
Onward,
The Platform,
Emma.,
The Illusionist,
Insidious,
Insidious: Chapter 2,
Insidious: Chapter 3,
The Notebook,
The Great Gatsby,
10 Things I Hate About You,
Black Swan,
The Second Mother,
Animal Kingdom,
Good Time,
Last Man Standing,
Kiss Kiss Bang Bang,
Drive,
The Town,
The Score,
Lock, Stock and Two Smoking Barrels,
Layer Cake,
American Hustle,
Killing them Softly,
Point Break,
Mean Streets,
In Bruges,
Easy Rider,
New Jack City,
Sin City,
The Thomas Crown Affair,
Traffic,
Donnie Brasco,
Matchstick Men,
Eastern Promises,
Blow,
Jackie Brown,
True Romance,
RocknRolla,
Menace II Society,
The Sting,
Road to Perdition,
Ronin,
Blow Out,
The Bad Sleep Well,
Gangs of New York,
Thief,
Chinatown,
Touch Of Evil,
The French Connection,
American Gangster,
Carlito’s Way,
Training Day,
City of God,
Casino,
Once Upon a Time in America,
L.A. Confidential,
Goodfellas,
Heat,
Fear City: New York vs the Mafia,
The Business of Drugs,
Children of Men,
Boogie Nights,
Almost Famous,
The Breakfast Club,
This Is Spinal Tap,
Manhattan,
All That Jazz,
Dawn of the Dead,
The Holy Mountain,
The Wild Bunch,
Night of the Living Dead,
In the Heat of the Night,
Charade,
Spartacus,
Breathless,
Paddington 2,
Kubo and the Two Strings,
Manchester by the Sea,
Rogue One: A Star Wars Story,
The Hateful Eight,
Big Hero 6,
The Broken Circle Breakdown,
The Wind Rises,
How to Train Your Dragon 2,
I Saw the Devil,
The Girl with the Dragon Tattoo,
Captain Phillips,
The Man from Nowhere,
Straight Outta Compton,
The Boy in the Striped Pajamas,
Mr. Nobody,
Little Miss Sunshine,
Pride & Prejudice,
Tokyo Godfathers,
Walk The Line,
Serenity,
The Triplets of Belleville,
The Count of Monte Cristo,
Walking Life,
Cast Away,
The Boondock Saints,
Open Your Eyes,
Fireworks,
Gattaca,
The Game,
Breaking the Waves,
Ed Wood,
Tombstone,
The Sandlot,
Naked,
The Fugitive,
Misery,
Awakenings,
Uncle Tom,
Tread,
The Fight,
Out of Shadows,
The Speed Cubers,
The Weight of Gold,
Father Soldier Son,
Earthlings,
Rebuilding Paradise,
Athlete A,
The Go-Go's,
Showbiz Kids,
Spaceship Earth,
Free Solo,
Mucho Mucho Amor: The Legend of Walter Mercado,
Bob Lazar: Area 51 & Flying Saucers,
Three Identical Strangers,
The Photo-Drama of Creation,
John Lewis: Good Trouble,
They Shall Not Grow Old,
Disclosure,
Stockton on My Mind,
I Am Not Your Negro,
You Don't Nomi,
Icarus,
Honeyland,
Unacknowledged,
Grizzly Man,
Miss Americana,
We Are Freestyle Love Supreme,
The Booksellers,
My Truth: The Rape of Two Coreys,
Demon House,
Baraka,
Blackfish,
Pumping Iron,
A Secret Love,
Shoah,
Touching the Void,
Missing 411,
Sour Grapes,
O.J.: Made in America,
Woodstock,
Zappa,
The Inventor: Out for Blood in Silicon Valley,
Paradise Lost: The Child Murders at Robin Hood Hills,
Crumb,
Bloody Nose Empty Pockets,
Our Godfather,
Fahrenheit 9 11,
The Red Pill,
Wrinkles the Clown,
Tickled,
Waltz with Bashir,
Elephant,
The Salt of the Earth,
Echo in the Canyon,
Triumph of the Will,
Circus of Books,
The Dissident,
Welcome to Chechnya,
Last Breath,
Marianne & Leonard: Words of Love,
Beware the Slenderman,
Once Is Enough,
Anelka: Misunderstood,
Minding the Gap,
Holy Hell,
What the Health,
Diego Maradona,
The Kingmaker,
Everybodys Everything,
My Scientology Movie,
Capital in the Twenty-First Century,
The Silence of Others,
Faces Places,
Dominion,
Capturing the Friedmans,
Voyeur,
The Cove,
Framing John DeLorean,
Get Me Roger Stone,
Again Once Again,
Hail Satan?,
House of Cardin,
Room 237,
The Girl on the Bridge,
Stop Making Sense,
The Thin Blue Line,
Samsara,
Inner Worlds, Outer Worlds,
Owned & Operated,
Neurons to Nirvana,
Dear Zachary A Letter to a Son About His Father,
The Two Escobars,
Blood Brother,
The Act of Killing,
The Look of Silence,
Virunga,
Won't You Be My Neighbor,
Man on Wire,
Amazing Grace,
Life Itself,
Minding the Gap,
Faces Places,
Three Identical Strangers,
McQueen,
Weiner,
20 Feet From Stardom,
The Last Waltz,
Knock Down the House,
Kedi,
Blackfish,
Taxi to the Dark Side,
Maiden,
Finders Keepers,
For the Bible Tells Me So,
Blindsight,
Rodents of Unusual Size,
The Island President,
The Devil Came on Horseback,
Pick of the Litter,
Mea Maxima Culpa: Silence In The House Of God,
Marwencol,
Undefeated,
Stories We Tell,
Bombshell: The Hedy Lamarr Story,
The Overnighters,
Beware Of Mr. Baker,
Call Me Kuchu,
Hale County This Morning, This Evening,
Sicko,
The Beatles: Eight Days a Week - The Touring Years,
Jafar Panahi's Taxi,
The War Tapes,
Muscle Shoals,
Cave of Forgotten Dreams,
Bowling for Columbine,
Murderball,
Tower,
Shirkers,
Inside Job,
Anvil! The Story of Anvil,
Tea With the Dames,
The Square,
Seymour: An Introduction,
Jiro Dreams of Sushi,
The Missing Picture,
Deliver Us from Evil,
Paris Is Burning,
One Child Nation,
Hoop Dreams,
Waste Land,
Waltz with Bashir,
Citizenfour,
The Interrupters,
Afghan Star,
Strong Island,
Jodorowsky's Dune,
Mr. Death The Rise and Fall of Fred  Leuchter,
Iris,
Capturing the Friedmans,
Project Nim,
The Invisible War,
RBG,
Sound City,
Elaine Stritch: Shoot Me,
56 Up,
Last Train Home,
My Journey Through French Cinema, 
The Look of Silence, 
Everyday Sunshine: The Story of Fishbone, 
Nostalgia for the Light, 
Spellbound, 
We Were Here, 
The Act Of Killing, 
Enron: The Smartest Guys in the Room,
Bill Cunningham New York, 
Rivers and Tides: Andy Goldsworthy Working With Time, 
Ai Weiwei: Never Sorry, 
13th, 
How to Survive a Plague, 
When We Were Kings, 
American Factory, 
This Is Not a Film, 
March of the Penguins, 
Hitchcock/Truffaut, 
Kurt Cobain: Montage Of Heck, 
Restrepo, 
The King of Kong: A Fistful of Quarters, 
The Fog of War Eleven Lessons from the Life of Robert S. McNamara,
The Panama Papers,
LA 92,
The Scheme,
Hoaxed,
Amanda Knox,
The Endless Summer,
Collective,
An Inconvenient Truth,
Casting JonBenet,
On the Record,
We Need to Talk About AI,
Super Size Me 2: Holy Chicken,
The Edge of Democracy,
Buena Vista Social Club,
Untouchable,
Deep Web,
20 Feet from Stardom,
Zero Days,
American Movie,
Endgame 2050,
Inside Deep Throat,
Gimme Shelter,
The Farthest,
Midnight Family,
The Abolitionists,
Aliens of the Deep,
West of Memphis,
Foosballers,
The Hunting Ground,
Gimme Danger,
The Queen of Versailles,
Scheme Birds,
Drunk Stoned Brilliant Dead,
Capitalism: A Love Story,
The Black Godfather,
City of Ghosts,
The Hangover,
Wedding Crashers,
The Hangover Part II,
The Hangover Part III,
Ted,
The 40-Year-Old Virgin,
Harold & Kumar Go to White Castle,
Harold & Kumar Escape from Guantanamo Bay,
Road Trip,
Idiocracy,
Friday,
Meet the Parents,
Napoleon Dynamite,
Knocked Up,
Super Troopers,
Office Space,
Baywatch,
War Dogs,
Long Shot,
Spy,
Dude, Where's My Car,
Clerks,
The Gentlemen,
Parasite,
The Rum Diary,
Fear and Loathing in Las Vegas,
Sweeney Todd: The Demon Barber of Fleet Street,
Rango,
Once Upon a Time in Mexico,
The Ninth Gate,
Ice Age,
Hellboy,
Hellboy II: The Golden Army,
Biutiful,
Megamind,
The Skin I Live In,
Starry Starry Night,
Ray,
No Man's Land,
Chicago,
Machete,
The Aviator,
Million Dollar Baby,
3:10 to Yuma,
Tupac: Resurrection,
8 Mile,
Notorious,
The Sea Inside,
Hustle & Flow,
Capote,
Crash,
American History X,
Syriana,
Babel,
Letters from Iwo Jima,
The Last King of Scotland,
Blood Diamond,
The Tree of Life,
The Bodyguard,
Deja Vu,
Friday the 13th,
Halloween,
The Texas Chain Saw Massacre,
Freddy vs. Jason,
Friday the 13th: The Final Chapter,
Friday the 13th Part VI: Jason Lives,
Friday the 13th Part III,
Beauty and the Beast,
The Transporter,
Three Extremes,
J. Edgar,
Mirrors,
Lord of War,
National Treasure,
Death Proof,
Planet Terror,
8MM,
Harry Potter and the Sorcerer's Stone,
Harry Potter and the Chamber of Secrets,
Harry Potter and the Prisoner of Azkaban,
The Machinist,
Legends of the Fall,
Ace Ventura: Pet Detective,
The Truman Show,
Me, Myself & Irene,
How the Grinch Stole Christmas,
Transformers,
Mission: Impossible,
Mission: Impossible II,
Sunshine,
Meet the Fockers,
Zodiac,
Underworld,
1408,
1900,
21 Grams,
300,
Ali G Indahouse,
American Pie,
American Pie 2,
Analyze This,
You've Got Mail,
The Ladykillers,
Get Him to the Greek,
The Road,
As Good as It Gets,
The Bucket List,
Mars Attacks!,
Wolf,
The Irishman,
Hoffa,
A Few Good Men,
Cashback,
The Cell,
Burn After Reading,
The Bank Job,
Constantine,
King of California,
The Crow,
Cube,
Dawn of the Dead,
Resident Evil,
Desperado,
Once Upon a Time in Mexico,
The Devil's Advocate,
Die Hard 2,
First Blood,
Rambo,
Dogville,
Downfall,
The Fifth Element,
The Fountain,
The Gods Must Be Crazy,
The Invasion,
The Last Samurai,
Kung Fu Hustle,
Paranormal Activity,
Saw,
Saw II,
Red Dragon,
Hannibal,
Predator,
From Hell,
In Time,
Ju-on: The Grudge,
A Very Harold & Kumar Christmas,
Home Alone,
House of Wax,
Repo Men,
Street Kings,
Vantage Point,
Panic Room,
Limitless,
Man On Fire,
Mystic River,
The Others,
Paul,
Psycho,
Thank You for Smoking,
V for Vendetta,
Watchmen,
Dorian Gray,
Hitch,
Unbreakable,
The Mist,
Blade Runner,
Blade Runner 2049,
West Side Story,
A Time to Kill,
The Good German,
Tango & Cash,
Platoon,
Armageddon,
Bullet,
How High,
Black Irish,
Fido,
Prince of Persia: The Sands of Time,
Good Morning, Vietnam,
Devils on the Doorstep,
The Raid: Redemption,
The Day of the Jackal,
The Lorax,
Ink,
Before the Devil Knows You're Dead,
There Will Be Blood,
Coraline,
Total Recall,
127 Hours,
La Haine,
Agora,
2001: A Space Odyssey,
Stalker,
Planet of the Apes,
Cloudy with a Chance of Meatballs,
Madagascar,
The Dark Knight Rises,
Over the Hedge,
Bee Movie,
Dark City,
The Dictator,
O Brother, Where Art Thou?,
Orphan,
Barry Lyndon,
The Thin Red Line,
Sleepy Hollow,
Beetlejuice,
The Believer,
A Room with a View,
Absolute Power,
A Perfect World,
The Witches of Eastwick,
Wall Street,
Thelma & Louise,
The Man from Earth,
Argo,
The Sting,
Intimate Stories,
Murder on the Orient Express,
Dances with Wolves,
Blue Velvet,
Wild at Heart,
Inland Empire,
Shaun of the Dead,
A Fistful of Dollars,
Mean Streets,
For a Few Dollars More,
Get Carter,
A Single Man,
Being There,
The Wild Bunch,
Prometheus,
JFK,
Neds,
Milk,
Malcolm X,
Amores Perros,
Gladiator,
Aliens,
Alien: Resurrection,
The Terminator,
Terminator 2: Judgment Day,
Terminator 3: Rise of the Machines,
Memories of Murder,
The Return,
I Saw the Devil,
Children of Heaven,
A Separation,
Network,
Raging Bull,
The Thing,
The Quiet Earth,
The Color Purple,
Brazil,
Philadelphia,
Natural Born Killers,
Buffalo '66,
Slumdog Millionaire,
District 9,
The Great Debaters,
Paul,
Phone Booth,
Melancholia,
Memoirs of a Geisha,
Enemy of the State,
Anna and the King,
The Golden Compass,
War Horse,
Stargate,
The Butterfly Effect,
River’s Edge,
The Purple Rose of Cairo,
Matewan,
Suburbia,
Eureka,
Sex, Lies and Videotape,
Miracle Mile,
After Hours,
The Forest Of Love,
Klaus,
Paddleton,
Tell Me Who I Am,
I Lost My Body,
System Crasher,
Marriage Story,
Uncut Gems,
Ms .45,
Joint Security Area,
The Taking of Pelham One Two Three,
The Bird with the Crystal Plumage,
Rolling Thunder,
Bullit,
Fist of Fury,
The Getaway,
Amer,
Seraphim Falls,
The Salvation,
Purgatory,
Conagher,
The Big Gundown,
The Missouri Breaks,
In a Valley of Violence,
Meek’s Cutoff,
The Great Silence,
The Wailing,
Tumbbad,
I See You,
Deathgasm,
Hell House LLC,
Southbound,
Mermaid Down,
Braid,
The Night Eats the World,
The Seventh Seal,
Animal Factory,
King of Devil’s Island,
Last Light,
Brubaker,
Captives,
Bad Boys,
Starred Up,
Blindspotting,
Waves,
Wind River,
Captain Fantastic,
Pride,
The Lobster,
American Honey,
Krisha,
Eraserhead,
Mulholland Dr,
28 Days Later,
The One I Love,
Freaks,
How to Talk to Girls at Parties,
Starfish,
Vivarium,
Crumbs,
Parallel,
Imitation Girl,
The Vast of Night,
Possessor,
Birdman,
Birth,
Goodbye, Dragon Inn,
Dead Man’s Shoes,
Morvern Callar,
Wendy and Lucy,
The Headless Woman,
Fish Tank,
Synecdoche, New York,
SPL: Kill Zone,
The Sisters Brothers,
Under the Silver Lake,
An Evening with Beverly Luff Linn,
Cam,
Damsel,
Virus Tropical,
Thunder Road,
Shoplifters,
Sorry to Bother You,
Isle of Dogs,
The Favourite,
Mandy,
You Were Never Really Here,
The Rider,
Leave No Trace,
Suspiria,
Eighth Grade,
First Reformed,
Moonlight,
American Graffiti,
Rosemary's Baby,
12 Years a Slave,
Gravity,
Spirited Away,
The Hurt Locker,
Before Midnight,
Amour,
Grave of the Fireflies,
The Wild Child,
Amazing Grace,
Carlos,
Call Me by Your Name,
Inside Llewyn Davis,
The Decline of Western Civilization,
The Florida Project,
Annie Hall,
Leviathan,
The Killing,
Fantastic Mr. Fox,
The Ground Beneath My Feet,
A Serious Man,
The Guilty,
Saint Frances,
I Wish I Knew,
Corpse Bride,
The Wind Rises,
The Lighthouse,
Paranoid Park,
Palm Springs,
Ixcanul,
Taxidermia,
Spider,
Last and First Men,
Cutie and the Boxer,
The Flat,
It Follows,
Court,
Election,
Creed,
Relaxer,
War for the Planet of the Apes,
Face/Off,
Dogtooth,
Hunger,
Black Sabbath,
Michael Clayton,
Paris Is Burning,
On the Beach at Night Alone,
Love & Mercy,
Taste of Cherry,
Henry: Portrait of a Serial Killer,
Making Waves: The Art of Cinematic Sound,
Lucky,
The Force,
Deep Water,
The Endless,
Frost/Nixon,
Last Resort,
3 from Hell,
47 Meters Down: Uncaged,
Annabelle Comes Home,
Black Christmas,
Bliss,
Brightburn,
Child's Play,
Color Out of Space,
Countdown,
Crawl,
The Curse of La Llorona,
Daniel Isn't Real,
Doctor Sleep,
Don't Let Go,
Earthquake Bird,
Eli,
Escape Room,
Happy Death Day 2U,
Harpoon,
Haunt,
The Hole in the Ground,
Sweetheart,
Velvet Buzzsaw,
Carrie,
Curse of Chucky,
The Conjuring,
Dark Skies,
Dark Touch,
Discopath,
Willow Creek,
V/H/S/2,
`;

export default text;
